### ISSUE TITLE
Dose this package support request reply pattern?

### ISSUE THREAD

**Issue by hanieas** [ssi-anik/laravel-amqp#10]

**Comment by ssi-anik** [comment]
Sorry for the late response.

I assume you meant RPC. No, this package still doesn't support RPC.

**Comment by hanieas** [comment]
Thanks for your response.

Is it OK if I want to work on this feature?

**Comment by ssi-anik** [comment]
It's perfectly okay. Please add enough tests to cover all the scenarios.
