### ISSUE TITLE
Argument 1 passed to Anik\Laravel\Amqp\AmqpManager::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given

### ISSUE THREAD

**Issue by kksffn** [ssi-anik/laravel-amqp#2]
I try to use laravel-amqp with laravel/lumen api. When I try to publish a message (```` Amqp::publish($messages)```) I get the exception:
Argument 1 passed to Anik\Laravel\Amqp\AmqpManager::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given. 
Rewriting constructor of AmqpManager to __construct(Illuminate\Contracts\Foundation\Application $app) "solves" the problem.

**Comment by ssi-anik** [comment]
I am not getting it correctly. What is the difference between your suggestion and my implementation?

**Comment by ssi-anik** [comment]
I have tagged a new release with `v1.1`. Updating the package should fix your issue.

**Comment by kksffn** [comment]
Thank you, works perfect now.
